language:
  - java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
    - gnupg2

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.m2
  # Deployer binaries
  - $HOME/sbt
  - $HOME/ccr

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
  # Cleanup the project repository
  - rm -rf $HOME/.m2/repository/$GROUP_ID_PATH

before_install:
  - pip install --user codecov
  - curl $DEPLOYER_URL/codacity-coverage-report-install.sh | sh

script:
  - mvn clean compile test cobertura:cobertura

after_success:
  - codecov
  - java -cp $HOME/ccr/codacy-coverage-reporter-assembly.jar com.codacy.CodacyCoverageReporter -l Java -r target/cobertura/coverage.xml
  - curl $DEPLOYER_URL/codacity-coverage-report-clean.sh | sh
  - curl $DEPLOYER_URL/deploy.sh | bash

notifications:
  email:
    on_success: never
    on_failure: change