language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
    - gnupg2

cache:
  directories:
  - $HOME/.m2

before_cache:
  - rm -rf $HOME/.m2/repository/$GROUP_ID_PATH

before_install:
  - pip install --user codecov

script: mvn clean compile test cobertura:cobertura

after_success:
  - codecov
  - curl $DEPLOYER_URL/codacity-java-cobertura.sh | bash
  - curl $DEPLOYER_URL/deploy.sh | bash

notifications:
  email:
    on_success: never
    on_failure: change